### ISSUE TITLE
Alpine arm64 builds

### ISSUE THREAD

**Issue by jogerj** [Cisco-Talos/clamav-docker#48]
Since the following issues #5 #8 were closed, there are still no alpine builds for arm64. Is that intended? 

A comment from @micahsnyder https://github.com/Cisco-Talos/clamav-docker/issues/5#issuecomment-1371531980 also hinted that debian images would be used as main image instead of alpine. Is this still the direction of the project?

**Comment by micahsnyder** [comment]
@jogerj I'm trying to limit the scope of what we have to maintain. This is why I have suggested switching to use Debian for the main image. We don't have plans to build arm64 alpine images.

**Comment by rsundriyal** [comment]
Closing it. Please comment in case of any further questions.

**Comment by jogerj** [comment]
wouldn't using debian based images compromise on security? at least that's the appeal for alpine based images. otherwise if vulnerabilities introduced from debian based images are from irrelevant [packages](https://hub.docker.com/_/debian/tags?page=1&name=11-slim&ordering=-name), can't they be removed from the image?

if compatibility issues with alpine is mostly from musl, would alternatives like `redhat/ubi9-micro`  which uses glibc be viable as base image (both technically and legally)?

**Comment by micahsnyder** [comment]
I don't think of Debian as being any less secure than Alpine. Certainly Alpine's busybox has a long history of security issues. 

Debian images are larger than Alpine, however. My understanding is the size of the download is the primary reason many people choose Alpine.

**Comment by polarathene** [comment]
> My understanding is the size of the download is the primary reason many people choose Alpine.

Usually that, or argued about attack surface. Alpine images have had various issues in the past beyond the glibc vs musl concern, such as with how DNS is handled.

Performance is often worse and not taken into consideration (_a build with Rust for example takes 5 minutes with musl vs 2 on glibc, python perf has also been cited as poor_), the default memory allocator has also introduced a variety of issues too. Busybox utils can be unexpected for some when they're not aware of the same familiar commands from coreutils not having feature parity or behaving differently in implementation too 😅 

So it can seem appealing to users initially, especially with all the advice they'd come around online. But there's often various surprises like described above that hit later and may not be readily apparent it's due to running on Alpine.

---

Fedora and openSUSE can both build small images with glibc when using `dnf` / `zypper` rootfs installs to a scratch image. `ubi9-micro` is similar AFAIK.

Although I've observed `zypper` not behaving as well in that scenario, it's been adopted by `testssl.sh` project to migrate from Alpine to a glibc distro [with only about 60MB image size](https://github.com/drwetter/testssl.sh/issues/2299#issuecomment-1471704041). The Alpine image was 36MB for comparison, so hardly a big size concern.

Regarding the existing ClamAV [Alpine](https://hub.docker.com/r/clamav/clamav) vs [Debian](https://hub.docker.com/r/clamav/clamav-debian) image sizes, it's 30MB vs 90MB if we exclude the 220MB database layer at the end. 60MB / 20% difference, not that compelling of a savings to prefer Alpine in this case?

---

I arrived here not realizing ARM64 builds were published (_at a separate DockerHub repo for debian base images_), so disregard the above.

If anyone does want `clamav` on Alpine, if the package for it is available install it and then just copy over the database file from the debian ARM64 image, I assume that's compatible? [I've been doing that in the past the other way around](https://github.com/Cisco-Talos/clamav-docker/issues/8#issuecomment-1532428813) (_taking the database from the Alpine image, and adding it to Debian AMD64 + ARM64 image I maintain_)
