### ISSUE TITLE
LogFile needed ?

### ISSUE THREAD

**Issue by albundy83** [Cisco-Talos/clamav-docker#57]
Hello,

maybe the log file "activation" should not be done here for example:
https://github.com/Cisco-Talos/clamav-docker/blob/main/clamav/1.4/alpine/Dockerfile#L68

As we are under Container and usually file logs are not very needed....

**Comment by micahsnyder** [comment]
I agree, though I hesitate to change this since others may depend on the current behavior.

In the meantime, you can override the config files to customize the behavior by mounting your own config directory as described here https://docs.clamav.net/manual/Installing/Docker.html#controlling-the-container

**Comment by albundy83** [comment]
Hello,
I understand, maybe another time :)
